/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    IBiArrowRight: typeof import('~icons/bi/arrow-right')['default']
    IFaCheck: typeof import('~icons/fa/check')['default']
    IFaTimes: typeof import('~icons/fa/times')['default']
  }
}
